routes/web.php
<?php

use App\Http\Controllers\clienteController;
use App\Http\Controllers\Notificaciones;
use App\Http\Controllers\ventaProductoController;
use App\Http\Controllers\productosController;
use App\Http\Controllers\proveedorController;
use App\Http\Controllers\reporteVentaProductosController;
use App\Http\Controllers\reporteVentasController;
use App\Http\Controllers\RutasController;
use App\Http\Controllers\usuarioController;
use App\Http\Controllers\ventasController;
use App\Http\Controllers\serviciosController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('acercade');
});


Route::middleware(['auth'])->group(function () {



    /** 
     * Ruta para cargar los datos en pantalla.
     */

    /** 
     * Ruta para guardar  los datos en base de datos, 
     * deben de tener cuidado :v por quisas me equivoque en cada una de sus 
     * rutas asi que pues las componen a conforme esta en "usuarios"
     */
    Route::resource('/usuarios', usuarioController::class);
    Route::resource('/proveedores', proveedorController::class);
    Route::resource('/productos', productosController::class);
    Route::resource('/clientes', clienteController::class);
    Route::resource('/ventas', ventasController::class);
    Route::resource('/productos-ventas', ventaProductoController::class);
    Route::resource('/servicios-ventas', serviciosController::class);

    Route::resource('/reporte-ventas-servicios',reporteVentasController::class);
    Route::resource('/reporte-venta-productos',reporteVentaProductosController::class);
    Route::resource('/notificaciones',Notificaciones::class);

    /**
     * Rutas solo para AJAX :v 
     */
    //Route::post('/estado/todo',[usuarioController::class,'getCiudades'])->name('estados.todo');

    Route::post('/estado/todo', [proveedorController::class, 'getCiudades'])->name('estados.todo');
    Route::post('/municipio/todo', [proveedorController::class, 'getColonias'])->name('municipios.todo');
    Route::get('/users/get/{email}/{valuePrimary}',[usuarioController::class,'isExists'])->name('user.exists');
    Route::get('/proveedores/get/{email}/{valuePrimary}',[proveedorController::class,'isExists'])->name('proveedor.exists');
    Route::get('/reporte-ventas-servicios/servicios/por/{mes}/{anio}',[reporteVentasController::class,'getResumen'])->name('resumen.servicios');
    Route::get('/reporte-venta-productos/productos/por/{mes}/{anio}',[reporteVentaProductosController::class,'getResumen'])->name('resumen.productos');
    Route::get('/consultalarga/productos/por/{dia}/{mes}/{anio}',[reporteVentaProductosController::class,'reporteVentas'])->name('resumen.productos2');
    
   //Rutas para el modulo de ventas servicios
    Route::post('/estado/servicio',[serviciosController::class,'getCiudades'])->name('estado.servicio');
    Route::post('/municipio/servicio',[serviciosController::class,'getColonias'])->name('municipio.servicio');
    Route::post('/servicio/show', [serviciosController::class,'show'])->name('servicio.show');
    Route::post('/servicio/infoCliente', [serviciosController::class,'getInfoCliente'])->name('infoCliente.servicio');

    Route::post('/cliente/todo', [serviciosController::class, 'getCliente'])->name('cliente.todo');
    //Rutas para el modulo de ventas de productos
    Route::post('/producto/venta', [ventaProductoController::class, 'getProducto'])->name('producto.venta');
    Route::post('/producto/guardarventa', [ventaProductoController::class, 'realizarVenta'])->name('producto.guardarventa');
    Route::post('/producto/guardardetalleventa', [ventaProductoController::class, 'guardarDetalleVenta'])->name('producto.guardardetalleventa');
    
    Route::get('/ventas/get/{folio_v}',[reporteVentaProductosController::class,'getProductsAtFolio'])->name('ventas.folio');
    Route::get('/servicios/get/{servicio}',[reporteVentasController::class,'getServicesAtFolio'])->name('servicios.folio');
    //rutas para productos
    Route::post('/producto/detalles', [productosController::class, 'getDetalles'])->name('producto.detalles');
    Route::post('/municipios/proveedor',[productosController::class,'getMunicipios'])->name('municipios.proveedor');
    Route::post('/colonias/proveedor', [productosController::class, 'getColonias'])->name('colonias.proveedor');
    Route::get('/notificaciones/existencia/total',[Notificaciones::class,'existsNotify'])->name('productos.notificacionesTotal');
    Route::post('/agrega/proveedor', [productosController::class, 'setProveedor'])->name('agrega.proveedor');
    Route::post('/producto/cambiar', [productosController::class, 'cambiosProducto'])->name('producto.cambiar');
    Route::post('/producto/buscar', [productosController::class, 'existe'])->name('producto.buscar');
    Route::post('/producto/buscarcorreo', [productosController::class, 'existeCorreo'])->name('producto.buscarcorreo');
    

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
});

/**
 * Lo termine haciendo asi :,,,,,v queria pasarselo aun controlador,
 * y que en el controlador hiciera lo de la rutas, pero no pude :,,,,,,,v 
 * bueno no encontre como hacerlo, asi que mejor puse las rutas manualmente
 * 
 */
//Route::get('/usuarios',[usuarioController::class,'index']);

Auth::routes();

/** 
 * Rutas de comodin
 * 
 */
//Route::get('/{pagina}',[RutasController::class,'showView']);
Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/clientes.blade.php
@extends('rootview')

<!--Contenido del header.-->
@section('header-seccion')
  <!--Esta es la prte del boton de log out -->
  <x-header visible=true>
    <x-slot name="items">
        <x-itemsNavBar active='clientes' />
        </x-slot>
</x-header>
@endsection

<!-----------------------------Títulos de la tabla e información del usuario en sesión----------------------------->
@section('contenido')

    <h5 class="h5 text-star mt-5 ps-3">
        <span>&#128075;</span>   
        ¡Hola, {{ auth()->user()->name }}!
    </h5>
    <h5 class="h5 text-star mt-3 mb-5 ps-3 ">
        <span>&#128101;</span>
        Clientes
    </h5>
<!------------------------------------- Cuerpo de la página ----------------------------------->
    <div class="container-fluid mb-4">
    <!--Botones principales de busqueda y agregar-->        
        <form method="GET" action="{{route('clientes.index')}}" class="row d-flex justify-content-end">
            <div class="col-5">
                <input type="text" class="form-control" placeholder="Nombre del cliente que desea buscar" name="inputBusqueda">
            </div>
            <div class="col-auto">
                <button type="submit" class="btn btn-light d-flex ps-3 pe-3">
                    <span class="me-3">&#128269</span>  
                    Buscar
                </button>
            </div>
                <div class="col-auto">
                <button type="button" class="btn btn-light d-flex ps-3 pe-3" data-bs-toggle="modal" data-bs-target="#registroClienteModal">
                    <span class="me-3">&#10133;</span>
                    Agregar
                </button>
            </div>
        </form>
    </div>

<!-------------------------------------Seccion de la tabla---------------------------------->
    <div class="conteiner-fluid">
        <div class="col-12">
            <table class="table">
                <thead>
                    <tr>
                        <!--
                        Campos de la tabla
                        -->
                        @foreach ($camposVista as $campo)
                            <th scope="col">{{$campo}}</th>
                        @endforeach
                    </tr>
                </thead>
                <tbody>
                    <!--Aqui van los registros-->
                    @foreach($registrosVista as $cliente)
                        <!--Inicio de la Fila-->
                        <tr>
                            <!--ID de la tabla clientes-->    
                            <th scope="col">{{$cliente->idcliente}}</th>
                            <!--Los otros atributos de la tabla clientes-->
                            <td class="data">{{$cliente->nombre}}</td>
                            <td class="data">{{$cliente->apellidoPaterno}}</td>
                            <td class="data">{{$cliente->apellidoMaterno}}</td>
                            <td class="data">{{$cliente->telefono}}</td>
                            <!--Botones-->
                                <td>
                                <a class="btneditar" data-bs-toggle="tooltip" data-bs-placement="top" title="Editar">
                                    <button class="btn boton-editar" 
                                        data-id="{{$cliente->idcliente}}"
                                        data-nombre="{{$cliente->nombre}}"
                                        data-apellidop="{{$cliente->apellidoPaterno}}"
                                        data-apellidom="{{$cliente->apellidoMaterno}}"
                                        data-tel="{{$cliente->telefono}}"
                                        data-bs-toggle="modal"
                                        data-route-url="{{route('clientes.update',$cliente)}}" 
                                        data-bs-target="#editarClientesModal">
                                        <span>&#128394;</span>
                                    </button>
                                </td>
                            <td>
                            <a class="btnborrar" data-bs-toggle="tooltip" data-bs-placement="top" title="Borrar">
                            <form class="form-detele" action="{{route('clientes.destroy',$cliente)}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button type="submit" 
                                    class="btn delete" 
                                    data-id="{{$cliente->idcliente}}"
                                    data-nombre="{{$cliente->nombre}}"
                                    data-apellidop="{{$cliente->apellidoPaterno}}"
                                    data-apellidom="{{$cliente->apellidoMaterno}}"
                                    data-tel="{{$cliente->telefono}}"

                                    data-bs-toggle="modal" 
                                    data-bs-target="#confirmacionModal">
                                    <span>&#10060;</span>
                                </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            {{$registrosVista->links()}}
        </div>
    </div>

    <!----------------------------------Modal de registro de un cliente------------------------------->

    <x-modal idModal="registroClienteModal" tituloModal="Modulo para registrar un cliente" 
    rutaEnvio="{{route('clientes.store')}}" metodoFormulario="POST">
    <x-slot name="cuerpoModal">
        <p class="px-3">
            Formulario para registrar un cliente
        </p>

        <x-tag-obligatorios />

        <div class="container-fluid">
            <div class="row">
                @csrf
                
                <!--Input oculto para el IDE del cliente-->
                <input type="hidden" class="" placeholder="" aria-label="" aria-describedby="" id="inputIDCliente" name="idcliente">
                <x-input-normal expresion="Error, valor no admitido. Ejemplo: Alexis (Debe iniciar en mayúsculas)" class="col-md-12 col-sm-12" classesLabel="col-3" idInput="inputNombreCliente" type="text" texto="Nombre del Cliente" valor="{{old('nombre')}}" nombreInput="nombre" nombreError="nombre" onKeypress="return sololetras(event)" />           
                </div>
                <div class="row">
                <!--Columnas :v-->
                <x-input-normal expresion="Error, valor no admitido. Ejemplo: Ruiz (Debe iniciar en mayúsculas)" class="col-md-12 col-sm-12" classesLabel="col-3" idInput="inputApellidoPCliente" type="text" texto="Apellido Paterno" valor="{{old('apellidoPaterno')}}" nombreInput="apellidoPaterno" nombreError="apellidoPaterno" onKeypress="return sololetras(event)"/>
                <x-input-normal expresion="Error, valor no admitido. Ejemplo: Pérez (Debe iniciar en mayúsculas)" class="col-md-12 col-sm-12" classesLabel="col-3" idInput="inputApellidoMCliente" type="text" texto="Apellido Materno" valor="{{old('apellidoMaterno')}}" nombreInput="apellidoMaterno" nombreError="apellidoMaterno" onKeypress="return sololetras(event)" />
                <x-input-normal class="col-md-12 col-sm-12" classesLabel="col-3" idInput="inputNumTelefono" type="number" texto="Número de Teléfono" valor="{{old('telefono')}}" placeholder="Ej. 9514628538" nombreInput="telefono" nombreError="telefono" />
                </div>
           
        </div>
        </x-slot>
    <x-slot name="footerModal">
        <x-button-normal-form type="reset" estiloBoton="btn-outline-danger" texto="Cancelar" data-bs-dismiss="modal" />
        <x-button-normal-form type="submit" estiloBoton="btn-outline-primary" texto="Registrar" />

    <!--
        <button type="button" class="btn btn-light d-flex ps-3 pe-3" data-bs-dismiss="modal">
            <span class="me-2">&#10060;</span>
            Cancelar
        </button>
        <button type="submit" class="btn btn-light d-flex ps-3 pe-3">
            <span class="me-2">&#10004;</span>
            Registrar
        </button>
    -->
    </x-slot>
</x-modal>

<!----------------------------------Modal de confirmación de un cliente------------------------------->
<x-modalSimple idModal="confirmacionModal" tituloModal="¿Seguro que quieres borrar este registro?">
    <x-slot name="cuerpoModal"></x-slot>
    <x-slot name="footerModal">
        <x-button-normal-form type="reset" estiloBoton="btn-outline-danger" texto="Cancelar" data-bs-dismiss="modal" />
        <x-button-normal-form type="button" estiloBoton="btn-outline-primary" texto="Confirmar" id="botonModalConfirmacion" />
    </x-slot>
</x-modalSimple>

<!----------------------------------Modal de edición de un cliente------------------------------->

<x-modal idModal="editarClientesModal" tituloModal="Editar un cliente." 
rutaEnvio="" metodoFormulario="POST">
    <x-slot name="cuerpoModal">
        <p class="px-3">
            Formulario para editar un cliente
        </p>

        <x-tag-obligatorios />

        <div class="container-fluid">
            <div class="row">
                @csrf
                
                <input type="hidden" name="urlTemp" value="{{old('urlTemp')}}" id="urlTemp">
                @method('PUT')
                <!--Checar método PUT-->
                <!--Input oculto para el IDE del cliente-->
                <input type="hidden" class="" placeholder="" aria-label="" aria-describedby="" id="inputIDCliente" name="idcliente">
                <x-input-normal expresion="Error, valor no admitido. Ejemplo: Alexis (Debe iniciar en mayúsculas)" class="col-md-12 col-sm-12" classesLabel="col-3" idInput="inputNombreClienteEditar" type="text" texto="Nombre del Cliente" valor="{{old('nombreEditar')}}" nombreInput="nombreEditar" nombreError="nombreEditar" onKeypress="return sololetras(event)"/>
                </div>
                <div class="row">
                <!--Columnas :v-->
                <x-input-normal expresion="Error, valor no admitido. Ejemplo: Ruiz (Debe iniciar en mayúsculas)" class="col-md-12 col-sm-12" classesLabel="col-3" idInput="inputApellidoPClienteEditar" type="text" texto="Apellido Paterno" valor="{{old('apellidoPaternoEditar')}}" nombreInput="apellidoPaternoEditar" nombreError="apellidoPaternoEditar" onKeypress="return sololetras(event)"/>
                <x-input-normal expresion="Error, valor no admitido. Ejemplo: Pérez (Debe iniciar en mayúsculas)" class="col-md-12 col-sm-12" classesLabel="col-3" idInput="inputApellidoMClienteEditar" type="text" texto="Apellido Materno" valor="{{old('apellidoMaternoEditar')}}" nombreInput="apellidoMaternoEditar" nombreError="apellidoMaternoEditar" onKeypress="return sololetras(event)"/>
                <x-input-normal class="col-md-12 col-sm-12" classesLabel="col-3" idInput="inputNumTelefonoEditar" type="number" texto="Número de Teléfono" valor="{{old('telefonoEditar')}}" placeholder="Ej. 9514628538" nombreInput="telefonoEditar" nombreError="telefonoEditar" />
                </div>
        </div>
        </x-slot>
    <x-slot name="footerModal">
        <x-button-normal-form type="reset" estiloBoton="btn-outline-danger" texto="Cancelar" data-bs-dismiss="modal" />
        <x-button-normal-form type="submit" estiloBoton="btn-outline-primary" texto="Guardar" />
    </x-slot>
</x-modal>

<!---------------------------------------------------Modal ADVERTENCIA------------------------------------------------->
@if('noValido')
        <div class="modal" tabindex="-1" id="negacionModal">
        <div class="modal-dialog modal-lg modal-dialog-centered">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Registro no admitido</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p class="alert alert-danger" role="alert">
                    @error('noValido')
                        {{$message}}.
                    @enderror
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal" aria-label="Close">¡OK!</button>
            </div>
            </div>
        </div>
        </div>
@endif

@endsection



<!--En esta seccion van los scripts para cada una de las vistas-->
@section('scritps')
    <script src="./js/validaciones/clientes.js"></script>
    <script src="./js/modales/ModalConfirmClien.js"></script>
    <script src="./js/funciones/editarCliente.js"></script>
    <script src="./js/modales/Vnumeros.js"></script>
    


    @if($errors->hasAny('nombre', 'apellidoPaterno','apellidoMaterno', 'telefono'))
        <script>
            let modalRegistro = new bootstrap.Modal(document.getElementById('registroClienteModal'),null);
            modalRegistro.show();
        </script>
    @endif

    @if($errors->hasAny('nombreEditar', 'apellidoPaternoEditar', 'apellidoMaternoEditar', 'telefonoEditar'))
        <script>
            let modalEdicion = new bootstrap.Modal(document.getElementById('editarClientesModal'),null);
            modalEdicion.show();
        </script>
    @endif

    @if($errors->has('noValido'))
        <script>
            let modalEdicion = new bootstrap.Modal(document.getElementById('negacionModal'),null);
            modalEdicion.show();
        </script>    
    @endif

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/notificaciones.blade.php
@extends('rootview')

<!--Contenido del header.-->
@section('header-seccion')
<x-header visible=true>
  <x-slot name="items">
    <x-itemsNavBar active='notificaciones' />
  </x-slot>
</x-header>
@endsection

@section('contenido')
<!-- Elementos que muestran la información de la persona previamente al Log In -->
<h5 class="h5 text-star mt-5 ps-3">
  <span>&#128075;</span>
  ¡Hola, {{ auth()->user()->name }}!
</h5>
<h5 class="h5 text-star mt-3 mb-5 ps-3">
  <span>&#128276;</span>
  Notificaciones
  <span id="cantidad"></span>
</h5>


<!-- Genera las alertas/notificaciones para la vista de notificaciones-->
<div class="conteiner mt-3 d-flex justify-content-center">
  <div class="toast-container row mb-3 flex-column ">
    @foreach($productosEscasos as $notificaciones)
    <x-toast tituloNotificacion="{{$notificaciones['titulo']}}" tiempo="" nombreProducto="{{$notificaciones['producto']->nombre_producto}}" producto="{{$notificaciones['producto']->clave_producto}}" conclusion="{{$notificaciones['conclusion']}}">
    </x-toast>
    @endforeach

  </div>
</div>
@endsection
@section('scritps')
@endsection

resources/views/reporteVentaProductos.blade.php
@extends('rootview')

<!--Contenido del header.-->
@section('header-seccion')
<x-header visible=true>
    <x-slot name="items">
        <x-itemsNavBar active="Reportes" />
    </x-slot>
</x-header>
@endsection

@section('contenido')
<h5 class="h5 text-star mt-5 ps-3">
    <span>&#128075;</span>
    ¡Hola, {{ auth()->user()->name }}!
</h5>
<h5 class="h5 text-star mt-3 mb-5 ps-3 ">
    <span>&#128101;</span>
    Reporte Productos
</h5>

<div class="container-fluid mb-4">
    <form method="GET" action="{{route('reporte-venta-productos.index')}}" class="row d-flex justify-content-end">
        <!--Input de busqueda-->
        <div class="col-5">
            <input type="text" class="form-control" placeholder="ID del reporte" name="inputBusqueda" value="{{ old('inputBusqueda') }}">
        </div>
        <!--Selector de Mes-->
        <div class="col-auto">
            <div class="input-group mb-3">
                <label class="input-group-text" for="inputSelectorMes">Mes</label>
                <select class="form-select" id="inputSelectorMes" name="inputSelectorMes" value="{{ old('inputSelectorMes') }}">
                    <option value="0" selected>Seleccione un mes...</option>
                    <option value="1">Enero</option>
                    <option value="2">Febrero</option>
                    <option value="3">Marzo</option>
                    <option value="4">Abril</option>
                    <option value="5">Mayo</option>
                    <option value="6">Junio</option>
                    <option value="7">Julio</option>
                    <option value="8">Agosto</option>
                    <option value="9">Septiembre</option>
                    <option value="10">Octubre</option>
                    <option value="11">Noviembre</option>
                    <option value="12">Diciembre</option>
                </select>
            </div>
        </div>
        <!--Selector de Año-->
        <div class="col-auto">
            <div class="input-group mb-3">
                <label class="input-group-text" for="inputSelectorAnio">Año</label>
                <select class="form-select" id="inputSelectorAnio" name="inputSelectorAnio" value="{{ old('inputSelectorAnio') }}">
                    <option value="0" selected>Seleccione un año.</option>
                    @foreach($aniosDisponibles as $anio)
                    <option value="{{$anio->anio}}">{{$anio->anio}}</option>
                    @endforeach
                </select>
            </div>
        </div>

        <!--Boton de busqueda -->
        <div class="col-auto">
            <button type="submit" class="btn btn-light d-flex ps-3 pe-3">
                <span class="me-3">&#128269</span>
                Buscar
            </button>
        </div>
    </form>
    @if(auth()->user()->rol != "Ayudante")
    <div class="row justify-content-end mt-4">
        <div class="col-auto">
            <button type="submit" class="btn btn-light d-flex ps-3 pe-3" name="resumir" id="btn-resumir" data-bs-toggle="modal" data-bs-target="#InformacionResumida">
                <span class="me-3">&#x1f4dd;</span>
                Ver reporte
            </button>
        </div>
    </div>
    @endif
</div>

<!--Seccion de la tabla-->
<div class="conteiner-fluid">
    <div class="col-12">
        <table class="table">
            <thead>
                <tr>
                    <!--
                        Campos de la tabla
                        -->
                    @foreach ($camposVista as $campo)
                    <th scope="col">{{$campo}}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                <!--Aqui van los registros-->
                @foreach($registrosVista as $venta)
                <!--Inicio de la Fila-->
                <tr>
                    <!--ID de la tabla clientes-->
                    <th scope="col">{{$venta->folio_v}}</th>
                    <!--Los otros atributos de la tabla usuarios-->
                    <td>{{$venta->idusuario}}</td>
                    <td>{{$venta->fechayhora}}</td>
                    <td>
                        <button class="btn btn-information-sales" data-url-query="{{ route('ventas.folio',$venta) }}" data-bs-toggle="modal" data-bs-target="#InformacionModalProductos" title="ver detalles">
                            <span>&#128065;</span>
                        </button>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        {{$registrosVista->withQueryString()->links()}}
    </div>
</div>

<!------Era el modal de Borrar. xd-------->
{{--
    @component('components.modalSimple')
        @slot('idModal','confirmacionModal')
        @slot('tituloModal','¿Seguro que quieres borrar este registro?')
        @slot('cuerpoModal')
            <!-- Cuerpo del modal-->
        @endslot
        @slot('footerModal')
            <button type="button" class="btn btn-light d-flex ps-3 pe-3" data-bs-dismiss="modal">
                <span class="me-2">&#10060;</span>
                Cancelar
            </button>
            <button type="submit" class="btn btn-light d-flex ps-3 pe-3" id="botonModalConfirmacion">
                <span class="me-2">&#10004;</span>
                Confirmar
            </button>
        @endslot
    @endcomponent
 --}}

<!-- ########################## MODLA DE INFORMACION DE LA VENTA ################################################-->
<x-modalSimple idModal="InformacionModalProductos" tituloModal="Informaicon basica de la venta">
    <x-slot name="cuerpoModal">
        <div class="container-information">

        </div>
    </x-slot>
    <x-slot name="footerModal">
        <x-button-normal-form type="button" estiloBoton="btn-outline-primary" texto="Aceptar" data-bs-dismiss="modal" />
    </x-slot>
</x-modalSimple>
<!-------------------------------------  Seccion del modal de informacion resumida. -------------------------------------->
<x-modalSimple idModal="InformacionResumida" tituloModal="Resumen de la consulta.">
    <x-slot name="cuerpoModal">
        <div class="container-information px-3">

        </div>
    </x-slot>
    <x-slot name="footerModal">
        <x-button-normal-form type="button" estiloBoton="btn-outline-primary" texto="Cerrar" data-bs-dismiss="modal" />
    </x-slot>
</x-modalSimple>
@endsection

<!--En esta seccion van los scripts para cada una de las vistas-->
@section('scritps')
<script src="./js/funciones/informacionProductos.js"></script>
<script src="./js/reporteResumenes/resumenProductos.js"></script>
@endsection

resources/views/rootview.blade.php
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document @yield('titulopagina')</title>
    <link rel="stylesheet" href="./css/bootstrap.css">
    <link rel="stylesheet" href="./css/app.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
</head>

<body>
    <!--Barra de navegacion -->
    @yield('header-seccion')
    <!--Resto del contenido-->
    <div class="container">
        @yield('contenido')
    </div>


    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script> -->
    <script src="js\validaciones\validacionInputs.js"></script>
    <script src="js/bootstrap/bootstrap.bundle.js"></script>
    <script>
        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
        var tooltipList = tooltipTriggerList.map(function(tooltipTriggerEl) {
            return new bootstrap.Tooltip(tooltipTriggerEl)
        })
    </script>


    @if(!Request::is('login') && !Request::is(''))
    <script src="./js/jquery-3.6.0.min.js"></script>
    <script src="./js/minAjax.js"></script>
    <script src="./js/funciones/verificarNotificaciones.js"></script>
    @endif

    @yield('scritps')
</body>

</html>